# This is a basic workflow to help you get started with Actions

name: Build (Windows)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: install zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          cache: false

      - name: Get VapourSynth include
        run: |
          mkdir include/vapoursynth
          curl https://raw.githubusercontent.com/vapoursynth/vapoursynth/master/include/VapourSynth4.h -o include/vapoursynth/VapourSynth4.h

      - name: build
        run: |
          zig build -Doptimize=ReleaseFast -Dvsinclude=include
          cd zig-out\lib
          ls
