# This is a basic workflow to help you get started with Actions

name: Build (Windows)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: install zig
        run: |
          curl https://raw.githubusercontent.com/ScoopInstaller/Install/master/install.ps1 -o install.ps1
          irm get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin [-OtherParameters ...]
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop bucket add versions
          scoop install versions/zig-dev

      - name: Get VapourSynth include
        run: |
          mkdir include/vapoursynth
          curl https://raw.githubusercontent.com/vapoursynth/vapoursynth/master/include/VapourSynth4.h -o include/vapoursynth/VapourSynth4.h
      
      - name: build
        run: |
          zig build -Doptimize=ReleaseFast -Dvsinclude=include
          ls
